version: "3"
services:
  dev:
    container_name: $CONTAINER_NAME
    image: iimuz/python-dev:v3.7.0-pipenv1
    environment:
      USER_ID: $USER_ID
      GROUP_ID: $GROUP_ID
      TZ: $TIME_ZONE
    volumes:
      - src:/src
    working_dir: /src
    command: bash

volumes:
  src:
    driver_opts:
      type: none
      device: ${PWD}/../../
      o: bind
