#: import get_color_from_hex kivy.utils.get_color_from_hex

TestRoot

<TestRoot>
    StartScreen
        id: startscreen

<startscreen>
    BoxLayout:
        orientation: 'vertical'
        size: root.size

        Image:
            source: './image/movieList.jpg'

        BoxLayout:
            size_hint_y: 0.3
            padding: 20,30,20, 10
            Button:
                id: button1
                text: "レコメンド開始"
                font_size: 60
                on_press: app.root.go_checkScreen()


<checkscreen@BoxLayout>
    BoxLayout:
        orientation: 'vertical'
        size: root.size

        BoxLayout:
            Image:
                source: './image/starwars.jpg'
            BoxLayout:
                orientation: 'vertical'
                size_hint_x: 0.3
                TextInput:  # タグ情報表示部分
                    size_hint_y: 0.1                
                    font_size: 45
                    hint_text: 'タグ情報'
                TextInput:  # タグ情報表示部分
                    font_size: 30
                    hint_text: 'SF、冒険、アメリカ映画、2017年公開、宇宙戦争、シリーズ物、デイジー・リドリー、ライアン・ジョンソン'

        BoxLayout:
            size_hint_y: 0.3
            padding: 20,30,20, 10
            Button:
                id: button2
                text: "Good"
                font_size: 60
                on_press: pass
            Button:
                id: button3
                text: "Bad"
                font_size: 60
                on_press: pass

