#: import get_color_from_hex kivy.utils.get_color_from_hex

TestRoot

<TestRoot>
    StartScreen
        id: startscreen

<startscreen>
    BoxLayout:
        orientation: 'vertical'
        size: root.size

        Image:
            source: './image/movieList.jpg'

        BoxLayout:
            size_hint_y: 0.3
            padding: 20,30,20, 10
            Button:
                id: button1
                text: "レコメンド開始"
                font_size: 60
                on_press: app.root.go_checkScreen()


<checkscreen@BoxLayout>
    BoxLayout:
        orientation: 'vertical'
        size: root.size

        Image:
            source: './image/starwars.jpg'

        BoxLayout:
            size_hint_y: 0.3
            padding: 20,30,20, 10
            Button:
                id: button2
                text: "Good"
                font_size: 60
                on_press: pass
            Button:
                id: button3
                text: "Bad"
                font_size: 60
                on_press: pass

